version: '3.5'
services:
  web:
    build: .
    environment:
    - PORT=3000
    - MONGODB_URI=mongodb://mongo:27017/find-my-plate
    ports:
    - "3000:3000"
    entrypoint: /app/entry-point.sh
    command:
    - npm
    - start
    depends_on:
    - mongo
  mongo:
    image: mongo:latest
